config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  get "parking/index"

  resources :parking

  root "application#index"

  get "/registered", to: "parking#registered"
  get "/terms", to: "parking#terms"
  get "/privacy", to: "parking#terms"
  get "/admin", to: "admin#index"
  get "/admin/simple", to: "admin#simple"
  delete "/admin/delete/:id", to: "admin#destroy"
  get "/admin/show/:id", to: "admin#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_table.html.erb
<tr>
  <th scope="row"><a href="/admin/show/<%= car.id %>"><%= car.make %></a></th>
  <td><%= car.license %></td>
  <td><%= car.start_date %></td>
  <td><%= car.end_date %></td>
  <td><%= link_to '<i class="material-icons red-text">delete_forever</i>'.html_safe, url_for(action: :destroy, id: car.id), method: :delete, data: {confirm: I18n.t("admin.delete_confirmation")} %></td>
</tr>

app/views/admin/index.html.erb
<h2><%= I18n.t("admin.title") %></h2>

<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#past">Past</a></li>
        <li class="tab col s3"><a class="active" href="#today">Today</a></li>
        <li class="tab col s3"><a href="#future">Future</a></li>
      </ul>
    </div>

    <div id="past" class="col s12">
      <table class="table striped">
        <thead>
          <tr>
            <th scope="col"><%= I18n.t("parking.form.make") %></th>
            <th scope="col"><%= I18n.t("parking.form.license") %></th>
            <th scope="col"><%= I18n.t("parking.form.start_date") %></th>
            <th scope="col"><%= I18n.t("parking.form.end_date") %></th>
            <th><%= I18n.t("admin.delete") %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "table", collection: @past, as: :car %>
        </tbody>
      </table>
    </div>

    <div id="today" class="col s12">
      <% if @today.count > 0 %>
        <table class="table striped">
          <thead>
            <tr>
              <th scope="col"><%= I18n.t("parking.form.make") %></th>
              <th scope="col"><%= I18n.t("parking.form.license") %></th>
              <th scope="col"><%= I18n.t("parking.form.start_date") %></th>
              <th scope="col"><%= I18n.t("parking.form.end_date") %></th>
              <th><%= I18n.t("admin.delete") %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "table", collection: @today, as: :car %>
          </tbody>
        </table>
      <% else %>
      <div class="card-panel arrow-background-green">
        <span class="white-text"><%= I18n.t("admin.no_today") %></span>
      </div>
      <% end %>
    </div>

    <div id="future" class="col s12">
      <% if @future.count > 0 %>
      <table class="table striped">
        <thead>
          <tr>
            <th scope="col"><%= I18n.t("parking.form.make") %></th>
            <th scope="col"><%= I18n.t("parking.form.license") %></th>
            <th scope="col"><%= I18n.t("parking.form.start_date") %></th>
            <th scope="col"><%= I18n.t("parking.form.end_date") %></th>
            <th><%= I18n.t("admin.delete") %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "table", collection: @future, as: :car %>
        </tbody>
      </table>
      <% else %>
      <div class="card-panel arrow-background-green">
        <span class="white-text">
          <%= I18n.t("admin.no_future") %>
        </span>
      </div>
      <% end %>
    </div>

    <div id="download" class="col s12">
      <%= link_to "<i class=\"material-icons left\">file_download</i> #{I18n.t("admin.download")}".html_safe, admin_path(:format => "csv"), class: "waves-effect arrow-background-orange btn" %>
    </div>
  </div>

app/views/admin/show.html.erb
<h2><%= I18n.t("admin.title") %></h2>
<div class="car-details">
  <div class="row">
    <div class="col s12 m6">
      <div class="card arrow-background-grey">
        <div class="card-content white-text">
          <span class="card-title"><%= @registration.color %> <%= @registration.make %></span>
          <div class="registration-creation"><strong>Reservation created:</strong> <%= @registration.created_at %></div>
          <div class="start-date"><strong>Start Date:</strong> <%= @registration.start_date %></div>
          <div class="end-date"><strong>End Date:</strong> <%= @registration.end_date %></div>
          <div class="code"><strong>Code:</strong> <%= @registration.code %></div>
          <div class="unit"><strong>Unit:</strong> <%= @registration.unit %></div>
          <div class="license"><strong>License:</strong> <%= @registration.license %></div>
          <div class="contact"><strong>Contact:</strong> <%= @registration.contact %></div>
        </div>
        <div class="card-action">
          <a href="/admin" class="white-text">Back</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/simple.html.erb
<h2><%= I18n.t("admin.title") %></h2>

<div id="today" class="col s12">
  <% if @today.count > 0 %>
    <table class="table striped">
      <thead>
        <tr>
          <th scope="col"><%= I18n.t("parking.form.make") %></th>
          <th scope="col"><%= I18n.t("parking.form.license") %></th>
          <th scope="col"><%= I18n.t("parking.form.start_date") %></th>
          <th scope="col"><%= I18n.t("parking.form.end_date") %></th>
          <th><%= I18n.t("admin.delete") %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "table", collection: @today, as: :car %>
      </tbody>
    </table>
  <% else %>
    <%= I18n.t("admin.no_today") %>
  <% end %>
</div>